layout_spectrum: 0.4620573
typography_spectrum: 0.3963835
color:
  lightness: 0.1375433
  brandStrength: 0.7630692
  saturation: 0.2076414
  rhythmicContrast: 0.9403962
  brandColors:
    - '#0E0C0C'
    - '#F3EBDF'
    - '#912816'
    - '#395B39'
    - '#F19A31'
name: eldron algiers
